### ISSUE TITLE
Not saving data.

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/esx_datastore#1]
This is not saving data for me :(

**Comment by ElPumpo** [comment]
Too bad

**Comment by mortdudley** [comment]
See, this is why people don't respect you, ElPumpo…

**Comment by ElPumpo** [comment]
You mean "this is why people with 0 development knowledge, that think in their brain that ESX is plug & play for none-developers don't respect you", correct me if I'm wrong.

**Comment by mortdudley** [comment]
Well I mean, I have plenty of development knowledge and I know ESX isn’t just plug and play and yet I still don’t respect you. Plenty of other people in my shoes that feel the same. I mean seriously, with responses like the one you gave this guy (this is only just one example of many) it’s no surprise people feel the way they do about you.
