### ISSUE TITLE
Error line 88 upon server start

### ISSUE THREAD

**Issue by S7eezy** [ESX-Org/esx_datastore#15]
![image](https://user-images.githubusercontent.com/53881150/62883931-927b9600-bd35-11e9-868e-83da3570ba94.png)

conflicts between clothes / datastore maybe?

**Comment by S7eezy** [comment]
it makes clotheshops and property dressing unusable
![image](https://user-images.githubusercontent.com/53881150/62884016-c8b91580-bd35-11e9-9b02-e21e4c910eb1.png)

**Comment by MiKPT** [comment]
I have the same problem. xPlayer.identifier isn't esx native so that doesn't help either

**Comment by dutchkiller2000** [comment]
try to change `AddEventHandler('esx:playerLoaded', function(playerId, xPlayer)` 
to 
`AddEventHandler('esx:playerLoaded', function(xPlayer)`

in the server lua file
