### ISSUE TITLE
I don't know what's wrong

### ISSUE THREAD

**Issue by zarx1337** [ESX-Org/esx_datastore#3]
Error running system event handling function for resource esx_datastore: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:74: attempt to get length of a nil value (field '?') 
stack traceback: 
server/main.lua:74: in function 'GetDataStore' 
server/main.lua:98: in upvalue 'handler' 
citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174> 
stack traceback: 
[C]: in function 'error' 
citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow' 
citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>

**Comment by zarx1337** [comment]
Does anyone have a solution?

**Comment by ElPumpo** [comment]
You have not registered the datastore in db
